#
# secret.niklashook.fr configuration
#

Listen 3002
# LoadModule cgid_module modules/mod_cgid.so
# or LoadModule cgi_module modules/mod_cgi.so ???

<VirtualHost *:3002>
   <Directory "/var/www/secret">
      Options +ExecCGI
      AddHandler cgi-script .cgi
      AllowOverride None
      Require all granted
      # Requires mod_allowmethods
      AllowMethods GET POST
   </Directory>
   ServerName secret.niklashook.fr
   DocumentRoot "/var/www/secret"

   # CORS
   Header set Access-Control-Allow-Origin "https://secret.niklashook.fr"

   # Security headers
      # HSTS: Imposer l'utilisation du protocole https -> Déjà mis par hooknas
      # Header always set Strict-Transport-Security "max-age=31536000"

      # Content-Security-Policy
      Header always set Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'"

      # X-Frame-Options
      Header always set X-Frame-Options "SAMEORIGIN"

      # X-Content-Type-Options
      Header always set X-Content-Type-Options "nosniff"

      # Referrer-Policy
      Header always set Referrer-Policy "strict-origin"

      # Permissions-Policy
      Header set Permissions-Policy "fullscreen=(self), microphone=(), camera=(), geolocation=(), autoplay=(), accelerometer=(), gyroscope=(), magnetometer=(), midi=(), payment=(), usb=()"

   # Gestion du cache
      # S'il n'y a pas déjà une en-tête "Cache-Control" (setté par un script cgi par exemple), mettre un par défaut
      Header always setifempty Cache-Control "max-age=3600, private" 
      # Pour certains type de fichiers, modifier 
      <Files ~ "\.(gif|jpe?g|png|ico|svg)$">
         Header always set Cache-Control "max-age=31536000, public"
      </Files>
      <Files ~ "\.(js|htm?l|css)$">
         Header always set Cache-Control "max-age=2592000, private"
      </Files>

</VirtualHost>
